### ISSUE TITLE
Support Alphanumeric Captchas

### ISSUE THREAD

**Issue by Tethik** [Tethik/flask-session-captcha#33]

**Comment by alisharify7** [comment]
hi, can I work on this issue and create a PR for that?

@Tethik

**Comment by Tethik** [comment]
Feel free @alisharify7

**Comment by alisharify7** [comment]
> Feel free @alisharify7

done, i create a pr for that please review it
@Tethik

**Comment by Tethik** [comment]
Closed by #46
