### ISSUE TITLE
hi i'm using flask session captcha for one of my project! because my client dont want the captcha services from google! i need a help! How to reload the captcha without losing the data in Input Fields?

### ISSUE THREAD

**Issue by arun-arunisto** [Tethik/flask-session-captcha#36]

**Comment by Tethik** [comment]
Hi @arun-arunisto 

It's been a long time since I used this library myself. 

I think this is more a flask issue than a captcha specific one. You probably need to store your inputs and re-render the form with them inserted as part of the template.

**Comment by arun-arunisto** [comment]
thank you!!
